version: '3.8'

services:
  web-push:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - VAPI_PUBLC_KEY=${VAPID_PUBLIC_KEY}
      - VAPI_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPI_SUBJECT=${VAPID_SUBJECT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tried=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s