name = "worker-rust-dev"
main = "build/worker/shim.mjs"
compatibility_date = "2023-06-28"

[build]
command = "cargo install -f wasm-bindgen-cli --version 0.2.103 && cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB-DEV" # i.e. available in your Worker on env.DB
database_name = "casaparo-dev"
database_id = "14a0d526-a91e-44da-861c-2bd2e2a54b3b"
