name = "worker-rust"
main = "custom_build/worker.entry.js"
compatibility_date = "2025-09-01"
minify = false

[build.upload]
format = "modules"
dir = "custom_build"
main = "worker.entry.js"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

[build]
command = """cargo clean && \
cargo install --force wasm-bindgen-cli --version "=0.2.103" --locked && \
cargo install -q worker-build --version "=0.1.8" --locked && \
worker-build --release"""

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "casaparo"
database_id = "9f32bbb8-b727-499f-b323-de1c399466df"