name: Deploy to Cloudflare Workers and Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-to-cloudflare-worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Wrangler CLI
      run: npm uninstall -g @cloudflare/wrangler && npm install -g wrangler
      working-directory: ${{ github.workspace }}/api-server-wasm

    - name: Publish to Cloudflare Workers
      run: npm run deploy
      working-directory: ${{ github.workspace }}/api-server-wasm
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

